#!/bin/sh

set -e

[ -f /etc/default/v-graphite ] && . /etc/default/v-graphite

IS_UPGRADE=false

case "$1" in
	configure)
        [ -z "$V_USER" ] && V_USER="v-graphite"
        [ -z "$V_GROUP" ] && V_GROUP="v-graphite"
        if ! getent group "$V_GROUP" > /dev/null 2>&1 ; then
            addgroup --system "$V_GROUP" --quiet
        fi
        if ! id $V_USER > /dev/null 2>&1 ; then
            adduser --system  --home /usr/share/v-graphite --no-create-home \
            --ingroup "$V_GROUP" --disabled-password --shell /bin/false "$V_USER"
        fi

        # Prepare dirs, log-dir, data-dir and pid-file
        mkdir -p "$LOG_DIR" "$DATA_DIR"
        chown -R $V_USER:$V_GROUP "$LOG_DIR" "$DATA_DIR"
        chmod 755 "$LOG_DIR" "$DATA_DIR"
        touch "$PID_FILE"
        chown $V_USER:$V_GROUP "$PID_FILE"

        # If $1=configure and $2 is set, this is an upgrade
        if [ "$2" != "" ]; then
            IS_UPGRADE=true
        fi

        if [ "x$IS_UPGRADE" != "xtrue" ]; then
            if command -v systemctl >/dev/null; then
                echo "### NOT starting on installation, please execute the following statements to configure v-collect to start automatically using systemd"
                echo " sudo /bin/systemctl daemon-reload"
                echo " sudo /bin/systemctl enable v-graphite"
                echo "### You can start v-graphite by executing"
                echo " sudo /bin/systemctl start v-graphite"
            elif command -v update-rc.d >/dev/null; then
                echo "### NOT starting v-graphite by default on boot up, please execute"
                echo " sudo update-rc.d v-graphite defaults 95 10"
                echo "### In order to start v-graphite, execute"
                echo " sudo service v-graphite start"
            fi
        elif [ "$RESTART_ON_UPGRADE" = "true" ]; then

            echo -n "Restarting v-graphite service..."

            if command -v systemctl >/dev/null; then
                systemctl daemon-reload
                systemctl restart v-graphite || true

            elif [ -x /etc/init.d/v-graphite ]; then
                if command -v invoke-rc.d >/dev/null; then
                    invoke-rc.d v-graphite restart || true
                else
                    /etc/init.d/v-graphite restart || true
                fi
            fi
            echo " OK"

	    fi
	;;
esac
