#!/bin/sh

set -e

[ -f /etc/sysconfig/v-graphite ] && . /etc/sysconfig/v-graphite

startServer() {
  if [ -x /bin/systemctl ] ; then
    /bin/systemctl daemon-reload
		/bin/systemctl start v-graphite.service
	elif [ -x /etc/init.d/v-graphite ] ; then
		/etc/init.d/v-graphite start
	elif [ -x /etc/rc.d/init.d/v-graphite ] ; then
		/etc/rc.d/init.d/v-graphite start
	fi
}

stopServer() {
	if [ -x /bin/systemctl ] ; then
		/bin/systemctl stop v-graphite.service > /dev/null 2>&1 || :
	elif [ -x /etc/init.d/v-graphite ] ; then
		/etc/init.d/v-graphite stop
	elif [ -x /etc/rc.d/init.d/v-graphite ] ; then
		/etc/rc.d/init.d/v-graphite stop
	fi
}

# Initial installation: $1 == 1
# Upgrade: $1 == 2, and configured to restart on upgrade
if [ $1 -eq 1 ] ; then
	[ -z "$V_USER" ] && V_USER="v"
	[ -z "$V_GROUP" ] && V_GROUP="v"

	if ! getent group "$V_GROUP" > /dev/null 2>&1 ;
	then
        groupadd -r "$V_GROUP"
	fi

	if ! getent passwd "$V_USER" > /dev/null 2>&1 ;
	then
         useradd -r -g v -d /usr/share/v-graphite -s /sbin/nologin -c "v user for v-graphite and v-graphite" "$V_USER"
	fi

 	# Set user permissions
	mkdir -p /var/log/v-graphite /var/lib/v-graphite
	chown -R $V_USER:$V_GROUP /var/log/v-graphite /var/lib/v-graphite
	chmod 755 /var/log/v-graphite /var/lib/v-graphite

	# configuration files should not be modifiable by v-graphite user, as this can be a security issue
	chown -Rh root:$V_GROUP /etc/v-graphite/*
	chmod 755 /etc/v-graphite
	find /etc/v-graphite -type f -exec chmod 640 {} ';'
	find /etc/v-graphite -type d -exec chmod 755 {} ';'

  if [ -x /bin/systemctl ] ; then
    echo "### NOT starting on installation, please execute the following statements to configure v-graphite to start automatically using systemd"
    echo " sudo /bin/systemctl daemon-reload"
    echo " sudo /bin/systemctl enable v-graphite.service"
    echo "### You can start v-graphite by executing"
    echo " sudo /bin/systemctl start v-graphite.service"
  elif [ -x /sbin/chkconfig ] ; then
    echo "### NOT starting v-graphite by default on bootup, please execute"
    echo " sudo /sbin/chkconfig --add v-graphite"
    echo "### In order to start v-graphite, execute"
    echo " sudo service v-graphite start"
  fi
elif [ $1 -ge 2 ] ; then
  if [ "$RESTART_ON_UPGRADE" == "true" ]; then
    stopServer
    startServer
  fi
fi
